### ISSUE TITLE
Running deploy.php breaks css/media

### ISSUE THREAD

**Issue by AbsenceGameDev** [leafiny/cms#1]
As stated above, running deploy.php breaks css/media for me, on linux-based (Manjaro) server. 
It might just be my inexperience in setting up servers that is the issue, but I am not sure.

It creates symlinks but the symlinks still are not accessible even from /pub , meaning I can't access /admin/leafiny

**Comment by AbsenceGameDev** [comment]
Ignore this, I am pretty sure my permissions were broken, fixed now

**Comment by leafiny** [comment]
Hi Ario,

If you have any need, i welcome you to ask me :)

Documentation is being written : [https://docs.leafiny.com](https://docs.leafiny.com)

Regards,
Matthieu

**Comment by AbsenceGameDev** [comment]
Hey Matthieu,

The documentation is great to have, I had missed installing some php packages but have it all sorted now thanks to the docs!


One suggestion regarding the documentation: for the vhosts example, you should add another example for apache 2.4 where you  replace
```
Order deny, allow 
Allow from all
```

with
`Require all granted`

**Comment by leafiny** [comment]
Thanks, this is updated (with comment in vhost example).

I will also update on Leafiny in next release and break compatibility with Apache < 2.4
